### ISSUE TITLE
UserScript no longer works due to URL change of ChatGPT website

### ISSUE THREAD

**Issue by KOOSH4** [AlirezaF80/ChatGPT-RTL#2]
Thank you for the ChatGPT RTL UserScript, but it doesn’t work anymore because the ChatGPT website URL has changed to https://chatgpt.com/*. This update has caused the script to stop detecting the website, and it no longer applies RTL text adjustments.

Please update the UserScript to recognize https://chatgpt.com/* as the ChatGPT website URL.

**Comment by AlirezaF80** [comment]
@KOOSH4 
ChatGPT's UI has gotten better since I developed this, so I forgot about this!
but thanks for reporting, I'll check it out.
